hysky
fintegrate-practicum/inventory pull request #11
Opened 2024-04-02 06:50 UTC by chayakno

2024-04-02 06:52 UTC, tzippykovalsky commented
יכול להיות שאת יכולה להוסיף גם pre-push
כך:
"husky": {
"hooks": {
"pre-commit": "lint-staged",
"pre-push": "npm test"
}
}
אבל בגדול נראה שזה מצוין

2024-04-03 20:02 UTC, nechamaLearn requested changes
אנחנו נעבוד עם husky במסמך חיצוני ולא כחלק מהpackage.json

2024-04-10 12:14 UTC, chayakno commented
עדכנתי בcommit האחרון אשמח להערות.

2024-04-10 19:39 UTC, nechamaLearn approved these changes
וידאת שזה עובד, נכון?

2024-07-08 20:12 UTC, closed without merging