dispatch add component
fintegrate-practicum/inventory pull request #43
Opened 2024-06-04 06:55 UTC by chayakno

dispach לשמירת נתוני התופס
לא מושלם
מחכה לתמונות

2024-06-04 09:16 UTC, buzz-code commented on nest/react/src/App.tsx
> +      </p> */}
אם לא צריך את הרכיב הזה, תמחקי אותו, אין טעם לשים בהערה

את בטוחה שזה צריך להיות בעמוד הראשון של המערכת? לא אמורים לראות קודם את הטבלה?

2024-06-04 09:16 UTC, buzz-code commented on nest/react/src/components/ComponentForm.tsx
> +        //     alert("לא ניתן למכירה בנפרד")
למחוק

2024-07-07 22:20 UTC, nechamaLearn approved these changes

2024-07-07 22:37 UTC, nechamaLearn requested changes
כרגע הPR הזה לא עובד
מה הוא אמור לבצע?

2024-07-07 22:47 UTC, chayakno commented
הPR הזה מוכל ב PR #45
אם אני זוכרת נכון
ואינו שימושי כרגע...

‫בתאריך יום ב׳, 8 ביולי 2024 ב-1:37 מאת ‪nechamaLearn‬‏ <‪
***@***.***‬‏>:‬

> ***@***.**** requested changes on this pull request.
>
> כרגע הPR הזה לא עובד
> מה הוא אמור לבצע?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fintegrate-practicum/inventory/pull/43#pullrequestreview-2161937098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGVKED42K3DT4ZKBZKX25I3ZLG7KJAVCNFSM6AAAAABIX3XEF6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRRHEZTOMBZHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-07 22:55 UTC, closed without merging

2024-07-07 22:57 UTC, chayakno commented
Awesome, thanks for the update!

‫בתאריך יום ב׳, 8 ביולי 2024 ב-1:56 מאת ‪nechamaLearn‬‏ <‪
***@***.***‬‏>:‬

> Closed #43 <https://github.com/fintegrate-practicum/inventory/pull/43>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fintegrate-practicum/inventory/pull/43#event-13415174852>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGVKEDYF2LEKRTQ6ELO3UOTZLHBRBAVCNFSM6AAAAABIX3XEF6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTGQYTKMJXGQ4DKMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>