I button
fintegrate-practicum/inventory pull request #55
Opened 2024-06-24 18:12 UTC by rachelosh

ממשק כפתור- הערכים שישלחו כ- props לקומפוננטת הצגת מוצרים

2024-06-25 07:50 UTC, nechamaLearn requested changes
למה מחקת 3 קבצים???

2024-06-25 14:17 UTC, rachelosh commented
לא זוכרת שמחקתי קבצים, איזה קבצים נמחקו?

‫בתאריך יום ג׳, 25 ביוני 2024 ב-10:50 מאת ‪nechamaLearn‬‏ <‪
***@***.***‬‏>:‬

> ***@***.**** requested changes on this pull request.
>
> למה מחקת 3 קבצים???
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fintegrate-practicom/inventory/pull/55#pullrequestreview-2137756975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BED45OJEESAWMA2O7M2TP6LZJEOMFAVCNFSM6AAAAABJ2J6GSWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMZXG42TMOJXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-26 19:25 UTC, NechamyD approved these changes

2024-06-26 19:35 UTC, nechamaLearn commented
אם תסתכלי על רשימת הקבצים ששונו תראי שיש 3 קבצים שנמחקו בPR הזה!

2024-06-26 19:35 UTC, nechamaLearn commented
ו @NechamyD לא מאשרים PR בלי להבין מה קורה בו

2024-06-26 19:44 UTC, rachelosh commented
התכתבנו על זה בסלאק, זה קבצים שהיו מחוץ ל-nest,
בזמנו אמרת למחוק אותם

2024-06-26 19:45 UTC, nechamaLearn commented
אז הם בעצם לא קשורים למשימה
תוציאי את המשימה לPR אחר
ואת הPR הזה תשאירי לי לאישור אח"כ, כי יש בעיה במחיקה כמו שעשית עכשיו

‫בתאריך יום ד׳, 26 ביוני 2024 ב-22:44 מאת ‪rachelosh‬‏ <‪
***@***.***‬‏>:‬

> התכתבנו על זה בסלאק, זה קבצים שהיו מחוץ ל-nest,
> בזמנו אמרת למחוק אותם
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fintegrate-practicom/inventory/pull/55#issuecomment-2192502288>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDZDQBS4LQGRHXSUXCYP2J3ZJMKZ3AVCNFSM6AAAAABJ2J6GSWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJSGUYDEMRYHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-06 21:52 UTC, closed without merging