add buisnessId to get function
fintegrate-practicum/inventory pull request #93
Opened 2024-08-07 11:32 UTC by yael-hamburger

הוספתי לפונקציה get-
 שלא יקבל את כל המוצרים שקיימים בדטה בייס, אלא שיחייב לקבל את ה id של העסק וישלוף לפי זה

2024-08-08 10:02 UTC, shifra-gelfman requested changes

2024-08-08 10:02 UTC, shifra-gelfman commented on src/component/component.controller.ts
> +    }
מה זה המשתנה idOrBusiness 
 מה הכוונה של השם?

2024-08-08 10:09 UTC, yael-hamburger commented on src/component/component.controller.ts
> +    }
היה צורך בשני get שמקבלים פרמס ואין אופצי הלעשות שתי פונקציות Get בעלות אותו ניתוב, כי הוא לא ידע למי לגשת.
לכן עשיתי פונקציה אחת שמקבלת פרמס ובודקת-
 אם זה מסוג objectId היא שולחת לפונקציה בסרוויס ששולפת לפי ID 
אחרת
היא שולחת לפונקציה בסרוויס ששולפת לפי businessId שהוא מסוג string

2024-08-08 10:11 UTC, shifra-gelfman approved these changes

2024-08-08 18:32 UTC, buzz-code commented on src/component/component.controller.ts
> +    }
@yael-hamburger 
לא זאת הדרך
אפשר להגדיר 2 פונקציות עם ראוט נפרד
ראוט של גט יכול להיות בלי פרמטר (ואז מחזירים הכל) או עם פרמטר (ואז מחזירים לפי הid) או עם טקסט ופרמטר (כמו למשל business/:businessId)

2024-08-11 18:30 UTC, buzz-code approved these changes

2024-08-12 10:11 UTC, syankel approved these changes
עברתי ונראה מצויין ממש מובן!

2024-08-12 10:20 UTC, shifra-gelfman approved these changes

2024-08-12 10:20 UTC, merged